<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FourTaste.ApplicationCore\FourTaste.ApplicationCore.csproj" />
    <ProjectReference Include="..\FourTaste.Infrastructure\FourTaste.Infrastructure.csproj" />
  </ItemGroup>

</Project>
