<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <NoWarn>$(NoWarn);SA1600;SA1633;SA1649;SA1508;SA1518;SA1516;SA1028;SA1200;SA1306;SA1127;SA0001;CS0414</NoWarn>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
